# Generated by Django 5.2.17 on 2026-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(choices=[('chart', 'Gráfico'), ('users', 'Usuários'), ('headset', 'Atendimento'), ('robot', 'Automação'), ('shield', 'Compliance'), ('brain', 'Inteligência')], default='chart', max_length=20, verbose_name='Ícone')),
                ('summary', models.CharField(max_length=300, verbose_name='Resumo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order'],
            },
        ),
    ]
