# Generated by Django 5.2.17 on 2026-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('sector', models.CharField(choices=[('financeiro', 'Financeiro'), ('saude', 'Saúde'), ('varejo', 'Varejo'), ('industria', 'Indústria'), ('tecnologia', 'Tecnologia'), ('logistica', 'Logística')], max_length=20, verbose_name='Setor')),
                ('client', models.CharField(max_length=150, verbose_name='Cliente')),
                ('challenge', models.TextField(verbose_name='Desafio')),
                ('solution', models.TextField(verbose_name='Solução')),
                ('results', models.TextField(verbose_name='Resultados')),
                ('image', models.ImageField(blank=True, upload_to='cases/', verbose_name='Imagem')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
