# Generated by Django 5.2.17 on 2026-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Khaleon IA', max_length=100, verbose_name='Nome do site')),
                ('tagline', models.CharField(default='BPO inteligente com tecnologia de ponta', max_length=200, verbose_name='Slogan')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Título do hero')),
                ('hero_subtitle', models.TextField(verbose_name='Subtítulo do hero')),
                ('hero_cta_text', models.CharField(default='Fale conosco', max_length=50, verbose_name='Texto do botão hero')),
                ('hero_cta_url', models.CharField(default='/contato/', max_length=200, verbose_name='URL do botão hero')),
                ('about_title', models.CharField(default='Sobre a Khaleon IA', max_length=200, verbose_name='Título sobre')),
                ('about_intro', models.TextField(verbose_name='Introdução sobre')),
                ('mission', models.TextField(verbose_name='Missão')),
                ('vision', models.TextField(verbose_name='Visão')),
                ('values', models.TextField(verbose_name='Valores')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(default='contato@khaleon.com.br', max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp (apenas números)')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('map_embed', models.TextField(blank=True, verbose_name='Embed do mapa (iframe)')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description padrão')),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configuração do site',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Rótulo')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Membro da equipe',
                'verbose_name_plural': 'Equipe',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('text', models.TextField(verbose_name='Depoimento')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['order'],
            },
        ),
    ]
