# Generated by Django 5.2.17 on 2026-08-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='system_active',
            field=models.BooleanField(default=True, verbose_name='Exibir card do sistema'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='system_description',
            field=models.CharField(blank=True, default='Acesse sua plataforma de gestão financeira e acompanhe suas finanças em tempo real.', max_length=300, verbose_name='Descrição do sistema'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='system_title',
            field=models.CharField(default='Finanças Pessoais', max_length=100, verbose_name='Título do sistema'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='system_url',
            field=models.URLField(blank=True, verbose_name='URL do sistema'),
        ),
    ]
