# Generated by Django 5.2.17 on 2026-08-06 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(max_length=300, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Imagem')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
